version: "3.8"

networks: 
    localnet:


services: 
    nginx:
        image: nginx
        volumes: 
            - ./web/nginx/conf/:/etc/nginx/conf.d/
        ports: 
            - 8080:80
        environment: 
            - NGINX_HOST=codeshaper.local
            - NGINX_PORT=80
        networks: 
            - localnet
    web:
        build: ./web
        environment: 
            # - APACHE_RUN_USER=www-data
            - DB_HOST=db
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${APP_DATABASE}
        volumes: 
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports: 
            - 8081:80
        working_dir: ${APP_PATH_CONTAINER}
        networks: 
            - localnet
    nodejs:
        build: 
            context: ./web
            dockerfile: Node.Dockerfile
            args: 
                TARGET_PATH: ${APP_PATH_CONTAINER}
        volumes: 
            - ${FRONT_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        ports: 
            - 8082:3000
        networks: 
            - localnet

    db:
        image: mariadb
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${APP_DATABASE}
        volumes: 
            - ${DB_PATH_HOST}:/var/lib/mysql
        networks: 
            - localnet
    adminer:
        image: adminer
        restart: always
        ports: 
            - 8085:8080
        networks: 
            - localnet