version: "3.8"

services: 
    nginx:
        restart: always
        depends_on: 
            - nodejs
        image: nginx
        volumes: 
            - ./web/nginx/conf/:/etc/nginx/conf.d/
        ports: 
            - 8080:80
        environment: 
            - NGINX_HOST=codeshaper.local
            - NGINX_PORT=80
    web:
        depends_on: 
            - db
        build: ./laravel/
        restart: always
        environment: 
            # - APACHE_RUN_USER=0
            - DB_HOST=db
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${APP_DATABASE}
        volumes: 
            - ${BACK_PATH_HOST}:${APP_PATH_CONTAINER}
        ports: 
            - 8081:80
        working_dir: ${APP_PATH_CONTAINER}
    nodejs:
        depends_on: 
            - web
        build: 
            context: ./next-app/
            dockerfile: Dockerfile
            args: 
                TARGET_PATH: ${APP_PATH_CONTAINER}
        volumes: 
            - ${FRONT_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        ports: 
            - 8082:3000
    db:
        image: mariadb
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${APP_DATABASE}
        volumes: 
            - ${DB_PATH_HOST}:/var/lib/mysql
    adminer:
        depends_on: 
            - db
        image: adminer
        restart: always
        ports: 
            - 8085:8080
